#!/usr/bin/env bash
# init-env.sh — generate .env di server production CloudPanel
# Usage: bash init-env.sh
# Aman dijalankan berulang (tidak menimpa .env yang sudah ada, kecuali pakai FORCE=1)
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$APP_DIR"

ENV_FILE="$APP_DIR/.env"
EXAMPLE="$APP_DIR/.env.production.example"

if [ ! -f "$EXAMPLE" ]; then
  echo "❌ $EXAMPLE tidak ditemukan."
  exit 1
fi

if [ -f "$ENV_FILE" ] && [ "${FORCE:-0}" != "1" ]; then
  echo "ℹ️  .env sudah ada — tidak ditimpa. Hapus dulu atau set FORCE=1 untuk regenerate."
  echo "   Lokasi: $ENV_FILE"
  exit 0
fi

# Ambil PORT dari argumen atau default 3038
PORT="${1:-3038}"

# Generate SESSION_SECRET 96 hex chars
SECRET=$(node -e "console.log(require('crypto').randomBytes(48).toString('hex'))")

# Path absolut untuk DATABASE_PATH
DB_PATH="$APP_DIR/.data/portal.db"

# Pastikan folder .data ada
mkdir -p "$APP_DIR/.data"

# Tulis .env (replace example placeholder)
{
  echo "# Generated by init-env.sh pada $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  echo "PORT=$PORT"
  echo "NODE_ENV=production"
  echo ""
  echo "# Path absolut ke SQLite"
  echo "DATABASE_PATH=$DB_PATH"
  echo ""
  echo "# Session secret (96 hex chars) — generated"
  echo "SESSION_SECRET=$SECRET"
} > "$ENV_FILE"

# Set permission ketat (hanya owner yang bisa baca)
chmod 600 "$ENV_FILE"

echo "✅ .env dibuat di: $ENV_FILE"
echo "   PORT             = $PORT"
echo "   NODE_ENV         = production"
echo "   DATABASE_PATH    = $DB_PATH"
echo "   SESSION_SECRET   = ${SECRET:0:16}…(${SECRET: -8})"
echo "   permission       = $(stat -c %a "$ENV_FILE" 2>/dev/null || stat -f %A "$ENV_FILE")"
echo ""
echo "👉 Langkah selanjutnya:"
echo "   cd $APP_DIR"
echo "   npm ci                # install deps (termasuk devDependencies untuk build)"
echo "   npm run build         # build Next.js"
echo "   npm prune --omit=dev  # ringankan node_modules"
echo "   $HOME/.npm-global/bin/pm2 restart portal-kecamatan --update-env"
